services:
  api:
    environment:
      CONFIG_API_KEY: ${CONFIG_API_KEY}
      CONFIG_ENDPOINT: ${CONFIG_ENDPOINT}
    image: ghcr.io/tjdrbs205/odg-api:latest
    container_name: odg-image-api
    restart: unless-stopped
    networks: [ogidogi-net]

  web:
    image: ghcr.io/tjdrbs205/odg-web:latest
    container_name: odg-image-web
    restart: unless-stopped
    networks: [ogidogi-net]

networks:
  ogidogi-net:
    external: true
    name: ogidogi-net
