services:
  api:
    image: ghcr.io/tjdrbs205/odg-api:latest
    container_name: odg-image-api
    restart: unless-stopped
    networks: [ogidogi-net]

  web:
    image: ghcr.io/tjdrbs205/odg-web:latest
    container_name: odg-image-web
    restart: unless-stopped
    networks: [ogidogi-net]

networks:
  ogidogi-net:
    name: ogidogi-net
