services:
  api:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/odg-api:${API_TAG:-latest}
    container_name: odg-image-api
    restart: unless-stopped
    networks: [ogidogi-net]

  web:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/odg-web:${WEB_TAG:-latest}
    container_name: odg-image-web
    restart: unless-stopped
    networks: [ogidogi-net]

networks:
  ogidogi-net:
    name: ogidogi-net
